volumes:
    run:

services:
    server:
        image: stzups/server
        build:
            context: server
        ports:
            - 25565:25565
        volumes:
            - "run:/run"
    client:
        image: stzups/client
        build:
            context: client
    discord:
        image: stzups/discord
        build:
            context: discord